name: Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  purefinance-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: bloq/actions/notify-deploy-to-slack@v1
        with:
          app-name: Hemi Pure Finance
          environment: production
          reference: ${{ github.event.head_commit.message }}
          slack-mention: ${{ vars.SLACK_MENTION }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: 'started :stopwatch:'
      - uses: actions/checkout@v4
      - uses: bloq/actions/setup-node-env@v1
      - run: npm run build
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          port: ${{ secrets.HOSTINGER_PORT }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          source: site/out/*
          target: public_html/pure.finance
          rm: true
          strip_components: 2
      - if: ${{ !cancelled() }}
        uses: bloq/actions/notify-deploy-to-slack@v1
        with:
          app-name: Hemi Pure Finance
          environment: production
          slack-mention: ${{ vars.SLACK_MENTION }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ job.status == 'failure' && 'failed :boom:' || 'finished :ok:' }}
